name: simple_moment
description: A simple implementation of the Moment.js features for relative time.
version: 1.2.0
homepage: https://github.com/rinukkusu/simple_moment

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  test: ^1.3.0
